### ISSUE TITLE
when using native power management，error and crash！ 

### ISSUE THREAD

**Issue by lifsux** [johnnync13/Xiaomi-Mi-Air#150]
panic(cpu 0 caller 0xffffff800c09167c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x2c8a.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff812bfdb900 : 0xffffff800ba458f8 
0xffffff812c0c3c40 : 0xffffff800b9413f1 
0xffffff812c0c3cb0 : 0xffffff800b93fc2f 
0xffffff812c0c3d00 : 0xffffff800ba429f9 
0xffffff812c0c3d40 : 0xffffff800ba4225b 
0xffffff812c0c3d70 : 0xffffff800c02cae8 
0xffffff812c0c3da0 : 0xffffff800c02f9f9 
0xffffff812c0c3e00 : 0xffffff800c014d8a 
0xffffff812c0c3ea0 : 0xffffff800c0146b4 
0xffffff812c0c3ec0 : 0xffffff800b961565 
0xffffff812c0c3f40 : 0xffffff800b961091 
0xffffff812c0c3fa0 : 0xffffff800b8c513e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxonln=1 igfxonlnfbs=0x010203

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x000000000b600000
Kernel text base: 0xffffff800b800000
__HIB  text base: 0xffffff800b700000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 1249719088292

**Comment by Bixio999** [comment]
I have the same issue. In the last part of my log there are other infos: 

"last loaded kext at 33232883686712: >usb.cdc.acm	5.0.0 (addr 0xffffff7f8b6b8000, size 32768)
last unloaded kext at 33162460962026: ru.joedm.SMCSuperIO	1.1.3 (addr 0xffffff7f87563000, size 53248)
loaded kexts: "

I don't know if these can be useful. 

This happens every time I try to put in sleep the laptop. 
My Bluetooth is also broken (I'm using Clover), may there be a connection between these? I thought that because of another thread where a similar issue was discussed, and bluetooth kext was detected as origin. (I'm referring to [this](https://github.com/johnnync13/Xiaomi-Mi-Air/issues/131))

**Comment by johnnync13** [comment]
this is bluetooth kext. Report to creator kext
