### ISSUE TITLE
Does the trackpad support all gesture control?

### ISSUE THREAD

**Issue by digimon04** [johnnync13/Xiaomi-Mi-Air#23]
I am going to buy a Xiaomi notebook air 13.3" 2018. Just wanna know does the notebook support multi-touch and all gesture controls in mac OS?

**Comment by unknuwn** [comment]
Yes it does, only the open/close launchpad isn’t as smooth as on MacBooks... or on the mi notebook pro. Btw I’d suggest you to buy the mi notebook pro 2018 since there’s better support there, hardware is working generally better and you don’t have to worry about thermal issues, which make the air model not 100% usable for that reason!

**Comment by digimon04** [comment]
> Yes it does, only the open/close launchpad isn’t as smooth as on MacBooks... or on the mi notebook pro. Btw I’d suggest you to buy the mi notebook pro 2018 since there’s better support there, hardware is working generally better and you don’t have to worry about thermal issues, which make the air model not 100% usable for that reason!

Thanks for the reply. I saw someone at tonymacx86 said 12.5" model supports all gestures but 13.3" model only support single touch and scrolling. Could someone confirm that?

What does it mean by "not 100% usable"? Does it mean the laptop overheated?

**Comment by unknuwn** [comment]
With the lastest EFI released from johnnync13 here, the touchpad works great. As I told you before, only the open/close launchpad gesture is a bit laggy (but works!). I think it’s because of the mi air touchpad quality, and not a bad driver issue. 
Maybe the touchpad doesn’t recognize well the four fingers opening and closing on it.

As for scrolling, pinching in and out, swiping with two, three or four fingers, everything works great.

I’m 100% sure cause I tested it.

As for usability, yes, heating dissipation is the real issue in this notebook (even on the 2018 model). You can do pretty much everything with it, even playing GTA 5 with high settings, but heat will kill your machine.

That’s why I suggest you to look for the Mi Notebook Pro instead (which has better Hackintosh support, same powerful hardware and the right heating dissipation system) or for a cheaper alternative if you need portability and not so much power! :)

Hope this helps you!

**Comment by digimon04** [comment]
Thanks for the advice :) 
I might have to re-consider the 13.3" model and 15" Pro. One last question, how is the battery life of Mi Notebook Pro? It makes me think that Mi Notebook Pro is much more power consuming compared to the 13.3" Air because of the larger screen.

**Comment by unknuwn** [comment]
Not really cause you have bigger screen but also bigger battery which compensates. Also, don’t forget that on 2018 mi notebook pro you can undervolt which provides lower temperatures and longer battery life

**Comment by digimon04** [comment]
Just found that you said Aliexpress sells M2 adapters for WiFi and BT cards. Did you succeed installing this combo into Xiaomi Notebook Air?

**Comment by unknuwn** [comment]
Unluckily I didn’t try that cause there was no one who could help me investigating. Btw I sold my Mi Air now
