### ISSUE TITLE
XIAOMI air i7-8550  EFI camera does not work

### ISSUE THREAD

**Issue by JuggMonster** [johnnync13/Xiaomi-Mi-Air#55]
Hello
XIAOMI air i7-8550 macOS 10.15
I use this EFI ,I find the front camera does not work,and there is something wrong with the USB LAN,is there any solution?

**Comment by wilsonnkwan** [comment]
> Hello
> XIAOMI air i7-8550 macOS 10.15
> I use this EFI ,I find the front camera does not work,and there is something wrong with the USB LAN,is there any solution?

@JuggMonster Bro, I am facing the same issue, I believe the Front camera is because of the KEXT which I don't know how to solve. But for the USB Lan, it's not the EFI, it's the driver. Catalina didn't come with 32bit drivers, so USB Lan and USB Wifi wont work. My suggestion to you for the connectivity is to get a USB Wifi that is covered by Chris1111's adaptation. 

https://github.com/chris1111/Wireless-USB-Adapter-Clover

**Comment by owen0o0** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/issues/47

**Comment by wilsonnkwan** [comment]
Yup, confirmed, I used clover to change the model under SMBBios to 14.1, the camera worked

**Comment by johnnync13** [comment]
It is because, You should configure USB ports with hackintool. I don't have this laptop anymore, If you configure this, you can do pull request.

**Comment by Kyawkyawlin1998** [comment]
> Yup, confirmed, I used clover to change the model under SMBBios to 14.1, the camera worked

I have too 

camera not working on i7 8550U

can i fix it
