### ISSUE TITLE
Xioami Air13.3 2019 cannot boot into system with this EFI

### ISSUE THREAD

**Issue by learningendless** [johnnync13/Xiaomi-Mi-Air#60]
Is there anyone whose computer is Xiaomi Air 13.3 2019 boot into system with this EFI ?
Mine air13.3 cannot boot into system.

**Comment by AlexRuck** [comment]
Yes this EFI works like a charm on the Air 13.3 2019 Edition. But one question. Which Version is your SSD? Do you use the Samsung MZVLB256HAHQ? If yes then you cannot use macOS because Samsung PM981 M.2 Disk is not supported.

I‘ve replaced my PM981 disk with a Samsung 970 EVO 500 GB NVMe M.2 and now it works.

**Comment by learningendless** [comment]
> Yes this EFI works like a charm on the Air 13.3 2019 Edition. But one question. Which Version is your SSD? Do you use the Samsung MZVLB256HAHQ? If yes then you cannot use macOS because Samsung PM981 M.2 Disk is not supported.
> 
> I‘ve replaced my PM981 disk with a Samsung 970 EVO 500 GB NVMe M.2 and now it works.

I'm using Samsung 860 EVO. System has been installed with the orginal EFI in dmg image.
