### ISSUE TITLE
Bluetooth didnt work on mojave

### ISSUE THREAD

**Issue by ly0817** [johnnync13/Xiaomi-Mi-Air#71]
After the latest EFI installation, Bluetooth doesnt work on 14，could you tell me it's because of incompatibility？

**Comment by vimcaw** [comment]
This is because `IntelBluetoothFirmware.kext` release is compiled by 10.15 SDK, it's not available on a lower version of macOS.

See: https://github.com/zxystd/IntelBluetoothFirmware/issues/7

you can download 10.14 version here: https://github.com/zxystd/IntelBluetoothFirmware/files/4018076/IntelBluetoothFirmware.kext.10.14.zip

**Comment by ly0817** [comment]
I tried, but it didn't work. I asked the manufacturer of the package. He said it might be because usbports.kext

**Comment by johnnync13** [comment]
@vimcaw do you have usbports fix with bluetooth and new smbios? I sold this laptop for not having thunderbolt 3

**Comment by vimcaw** [comment]
@johnnync13 Sorry, I'm a noob in Hackintosh, but I can try to learn relative knowledge at my leisure.
