### ISSUE TITLE
keyboard are invalid, and Bluetooth will show no connection

### ISSUE THREAD

**Issue by ly0817** [johnnync13/Xiaomi-Mi-Air#87]
Keyboard F2, F3, F4, F5 volume and brightness are all invalid, and Bluetooth will show no connection after connecting the phone，macos 15.2，Do you have the same questions？

**Comment by yllwfsh** [comment]
Which version of the EFI folder are you using? Clover or Opencore? Try the latest: https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v6.6

Can you try pressing Fn+F2/F3/F4/F5 ? Does it work now? Maybe try toggling the mode using Fn+ESC.

For your Bluetooth issues, can you try describing your problem here: https://github.com/zxystd/IntelBluetoothFirmware/issues

If it's fixed, let us know!

**Comment by ly0817** [comment]
> Which version of the EFI folder are you using? Clover or Opencore? Try the latest: https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v6.6
> 
> Can you try pressing Fn+F2/F3/F4/F5 ? Does it work now? Maybe try toggling the mode using Fn+ESC.
> 
> For your Bluetooth issues, can you try describing your problem here: https://github.com/zxystd/IntelBluetoothFirmware/issues
> 
> If it's fixed, let us know!

ok，thanks
