### ISSUE TITLE
Enable HiDPI settings

### ISSUE THREAD

**Issue by timmmmmmmmm** [johnnync13/Xiaomi-Mi-Air#90]
I believe I finally got everything working. The biggest improvement for me was to buy a SATA drive and disable NVME as described in #68.
One of the last details I'm now stuck with is the tiny text and icons on the screen, as macOS just displays everything as is on the native Full HD resolution. On a previous Mojave installation I got the DPI scaling working using [this solution](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/one-key-hidpi) for the Pro laptop, but I can't get it to work on my current OC Catalina installation. Are there any modifications required?

**Comment by yllwfsh** [comment]
Good to hear that you have it working! I've adapted https://github.com/xzhih/one-key-hidpi to work on Catalina. The problem is with the SIP check on line 75. Apparently the output of the command changed between Mojave and Catalina. Let me know if it works for you so i can add it to this repo.

[hidpi.sh.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4218264/hidpi.sh.zip)

**Comment by yllwfsh** [comment]
In order to let the script run you have to disable SIP in the recovery partition, using Terminal and entering 'csrutil disable' then reboot. If the script still doesn't run, maybe boot with:

csr-active-config: E7030000 (enter using propertree)

Afterwards you can boot wit 00000000 and enable SIP with 'csrutil enable' in Recovery.

**Comment by timmmmmmmmm** [comment]
Awesome, got it working! Only had to go into recovery to do 'csrutil disable' and the script ran without problems.

**Comment by yllwfsh** [comment]
Cool! I'll add it to the repo then with some instructions. Thx for the feedback!

**Comment by yllwfsh** [comment]
See https://github.com/johnnync13/Xiaomi-Mi-Air/commit/99f3a93bc7c20d7d1de6cc9ea2d040ec0e3676a0 and https://github.com/johnnync13/Xiaomi-Mi-Air/commit/f149771eb3e5c762465d5cfc6729009e4f05fcd0
